name: Lord of Coverage

on:
  push:
    branches: [ '*' ]

jobs:
  build:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        node-version: [12.x, 10.x]

    steps:
      - name: Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          language: node_js
          scripts:
            npm install codecov -g
          after_success:
            codecov
          directory: Server/test/
          flags: unittests
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.gz

        


