name: Guardians of the Compiler

on:
  push:
    branches: [ master ]


jobs:
  build:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache client node modules
        uses: actions/cache@v1
        with:
          path: Client/
          key: ${{ runner.os }}-cnodes-${{ hashFiles('**package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cnodes-

      - name: Cache server node modules
        uses: actions/cache@v1
        with:
          path: Server/
          key: ${{ runner.os }}-snodes-${{ hashFiles('**package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-snodes-


      - name: Set-up Node version ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install server dependencies, run builds and test
        working-directory: Server/
        run: |
          npm ci
          npm run build
          npm run test

      - name: Install client dependencies, run builds and test
        working-directory: Client/
        run: |
          npm ci
          npm run build
#          npm run test

