name: Guardians of the Compiler

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set Node.js 12.x
        uses: actions/setup-node@master
        with:
          version: 12.x

      - name: Install server dependencies
        working-directory: Server/
        run: |
          npm ci

      - name: Build server
        working-directory: Server/
        run: |
          npm run build

      - name: run tests on server
        working-directory: Server/
        run: |
          npm run test

      - name: Install client dependencies
        working-directory: Client/
        run: |
          npm ci

      - name: Build server
        working-directory: Client/
        run: |
          npm run build

      - name: run test on server
          working-directory: Server/
          run: |
            npm run test
